import type { AmountView, MeterStatusCode, MeterTone } from "./view-model";
export declare function formatMicroCny(microCny: number, decimals?: number): string;
export declare function formatCurrencyMinor(amountMinor: number, currency?: string, decimals?: number): string;
export declare function formatTokenCount(tokens: number): string;
export declare function formatTokenBucketLabel(label: string): string;
export declare function createAmountView(microCny: number, decimals?: number, currency?: string): AmountView;
export declare function createUnknownAmountView(label?: string): AmountView;
export declare function createUnavailableAmountView(label?: string): AmountView;
export declare function formatStatusLabel(code: MeterStatusCode): string;
export declare function formatTone(code: MeterStatusCode): MeterTone;
